version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3030/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      # Don't override node_modules from the container
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - JWT_SECRET=gayantha-server
      - COUNTRY_API_URL=https://restcountries.com/v3.1
      - AUTH_TOKEN=c364f0bc8e4318114bb56be8089d0265
      - DB_DIRECTORY=/app/data
      - DB_FILENAME=traveltales.db
      - SQL_SCRIPT=/app/src/sql/init-db.sql
      - INTERNAL_SERVICE_URL=http://host.docker.internal:3000
    volumes:
      - ./backend/src:/app/src
      - traveltales_data:/app/data:rw
      # Don't override node_modules from the container
      - /app/node_modules
    command: >
      sh -c "node src/script/database.js && node src/server.js"
    networks:
      - app-network

volumes:
  traveltales_data:
    name: traveltales_data

networks:
  app-network:
    driver: bridge